truncate cnt_subscribe
truncate nnuser_report
truncate pdr
truncate poi_pdr
truncate captcha
truncate counter
truncate counter_shard
truncate mso
truncate mso_config
truncate nnchannel
truncate nnchannel_pref
truncate nnepisode
truncate nnprogram
truncate poi
truncate poi_campaign
truncate poi_event
truncate poi_map
truncate poi_point
truncate store_listing
truncate systag
truncate systag_display
truncate systag_map
truncate tag
truncate tag_map
truncate title_card
truncate ytprogram
truncate nnguest
truncate nnuser
truncate nnuser_pref
truncate nnuser_profile
truncate nnuser_subscribe
truncate nnuser_watched
truncate nnguest
truncate nnuser
truncate nnuser_pref
truncate nnuser_profile
truncate nnuser_subscribe
truncate nnuser_watched
